framework:
    asset_mapper:
        paths:
            - assets/
        excluded_patterns:
            - '*/.*'
        extensions:
            - .js
            - .css
        importmap_path: importmap.php
        missing_import_mode: strict
        server: true

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
            server: false
