framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: maison_provence

        # Utiliser APCu pour le cache système
        system: cache.adapter.apcu

        # Utiliser le filesystem pour le cache par défaut
        app: cache.adapter.filesystem

        # Pools de cache spécifiques
        pools:
            # Cache pour doctrine
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
            # Cache pour les traductions
            translations_pool:
                adapter: cache.app
            # Cache pour les assets
            assets_pool:
                adapter: cache.app
