# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    csrf_protection: true
    
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 100
        
    php_errors:
        log: true
        
    validation:
        email_validation_mode: html5
        
    http_cache:
        enabled: true
        default_ttl: 0
        
    serializer:
        enable_attributes: true
        
    mailer:
        message_bus: false

    lock:
        enabled: true
        resources:
            login_limiter:
                dsn: 'flock'
            api:
                dsn: 'flock'

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_psr6_provider: 'cache.provider.default'
        pools:
            cache.provider.default:
                adapter: cache.adapter.filesystem

    profiler:
        enabled: true
        collect: true
        only_exceptions: false
        only_main_requests: false
        dsn: 'file:%kernel.project_dir%/var/cache/%kernel.environment%/profiler'

when@dev:
    framework:
        profiler: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false
