# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    # configure resolvers
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~

        # Miniature pour l'équipe dans l'admin
        team_thumb:
            quality: 85
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true

        # Image complète pour l'équipe sur le site
        team_full:
            quality: 90
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound
                    allow_upscale: false
