framework:
    messenger:
        failure_transport: failed

        transports:
            async_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: priority
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            
            async_default:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: default
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction

        routing:
            'App\Message\ProcessImageMessage': async_priority
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async_default
            'Symfony\Component\Notifier\Message\ChatMessage': async_default
            'Symfony\Component\Notifier\Message\SmsMessage': async_default
            'App\Message\ExportOrdersMessage': async_default
