parameters:
    security.headers:
        x_frame_options: 'SAMEORIGIN'
        content_security_policy:
            - "default-src 'self'"
            - "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://ga.jspm.io blob:"
            - "script-src-elem 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://ga.jspm.io blob:"
            - "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com"
            - "img-src 'self' data: https://flowbite.com"
            - "connect-src 'self' https://127.0.0.1:* blob:"
            - "font-src 'self' https://cdnjs.cloudflare.com"
            - "worker-src 'self' blob:"

services:
    App\EventSubscriber\SecurityHeadersSubscriber:
        arguments:
            $params: '@parameter_bag'
        tags:
            - { name: kernel.event_subscriber }
