vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media_image:
            uri_prefix: /uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        team_photos:
            uri_prefix: /uploads/team
            upload_destination: '%kernel.project_dir%/public/uploads/team'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
