vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        media_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
        team_photos:
            uri_prefix: /uploads/team
            upload_destination: '%kernel.project_dir%/public/uploads/team'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
