parameters:
    upload_directory: '%kernel.project_dir%/var/test/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\:
        resource: '../tests/*'
        exclude: 
            - '../tests/bootstrap.php'
            - '../tests/Fixtures/*'  # Exclure explicitement les fixtures

    # Correction de la casse pour GenerateTestImage
    App\Tests\Fixtures\GenerateTestImage:
        public: true
        autowire: false
